### ISSUE TITLE
About the proxy address

### ISSUE THREAD

**Issue by fadewalk** [kellnr/kellnr#106]
Hi, bro. Currently, kellnr can only proxy https://crates.io/. Can it support proxying other mirror addresses? Just like the nexus proxy for pypi etc. Can it be configured in the configuration file?

**Comment by sinyo-matu** [comment]
Hi @fadewalk,
Could you please provide a description of your use-case? 
I'm curious about why it's valuable to proxy crates through another proxy.
Thank you!

**Comment by fadewalk** [comment]
> Hi @fadewalk, Could you please provide a description of your use-case? I'm curious about why it's valuable to proxy crates through another proxy. Thank you!

Some companies cannot access the external network internally, but they want to build a proxy to rust registry . like the nexus proxy func

**Comment by secana** [comment]
@fadewalk No, Kellnr can only proxy crates.io and support for other proxy types is currently not planned.
