### ISSUE TITLE
Display cached crates in UI

### ISSUE THREAD

**Issue by secana** [kellnr/kellnr#147]
Add a toggle to show crates from crates.io in the UI, too.

**Comment by secana** [comment]
Thanks for the feedback. I didn't plan to generate the docs for the cached crates, but I'll look into that.

**Comment by SpootDev** [comment]
I would love to see this feature enabled as well to allow looking at the cached crates.

**Comment by secana** [comment]
TODO:

- [ ] Add `max_version` column to `cratesio_crate` table
- [ ] Add `documentation` column to `cratesio_meta` table (link to docs.rs)
- [ ] Add icon to UI in `Crates` view, to distinguish between kellnr and crates.io crates (add icon to `CrateCard`)
- [ ] Add switch in UI in `Crates` view, to enable or disable the display and search of cached crates
- [ ] Add conditional search for cached crates to `search` endpoint in `web_ui.rs`

Q: How to handle, if the crate card is clicked in the UI?
1. Forward to the corresponding crates.io page
2. Show all details of the crate, like it is done for kellnr crates
  - All missing values need to be added to the DB

For the first iteration, linking to crates.io seems fine.

**Comment by secana** [comment]
Have to think about linking to crates.io as stated above, as the list of cached versions of a crate would not be accessibly with this approach. If a click on the `CrateCard` forwards to crates.io instead of opening the `Crate` view, which displays the available version, this information is lost to the user.

**Comment by secana** [comment]
For the first iteration, I decided to just link to crates.io. Everything else can be delivered if requested in later versions.
