### ISSUE TITLE
cargo deny check to run regular advisories checks in ci

### ISSUE THREAD

**Issue by tkoeppen** [kellnr/kellnr#148]
cargo deny check is a helpful tool to regular check outdated dependencies or 

https://github.com/EmbarkStudios/cargo-deny

The advisories check is used to detect issues for crates by looking in an advisory database.
The licenses check is used to verify that every crate you use has license terms you find acceptable.

It might be helpful for this project as well.

**Comment by secana** [comment]
thanks for the corresponding PR!
