### ISSUE TITLE
Internal server error on incorrect password

### ISSUE THREAD

**Issue by Schmebulock** [kellnr/kellnr#160]
When incorrect password is entered internal server error message is displayed instead of incorrect username or password message.

![obrazek](https://github.com/kellnr/kellnr/assets/21037263/ddd60b0d-b092-4272-a88a-581c63eb0e97)

Message in log:
ERROR web_ui::error: Db: PasswordMismatch
ERROR tower_http::trace::on_failure: response failed classification=Status code: 500 Internal Server Error latency=2 ms

**Comment by secana** [comment]
Hi @Schmebulock, thanks for reporting the bug. I'll fix it in the next Kellnr version.

**Comment by secana** [comment]
Fixed in Kellnr 5.1.0
