### ISSUE TITLE
Error when publishing to crates.io proxy

### ISSUE THREAD

**Issue by fuzzypixelz** [kellnr/kellnr#170]
First of all, cool project!

My use case is a CI process which publishes a set of inter-dependent crates to Kellnr to ensure that publishing is possible.

When enabling the crates.io proxy and attempting to publish to the proxy index (e.g. `sparse+http://localhost:8000/api/v1/cratesio/`), Cargo hangs while waiting for the crate to become available and Kellnr keeps printing the following error:

```console
ERROR index::cratesio_prefetch_api: Could not parse prefetch data from crates.io for test-kellnr: expected value at line 1 column 1
```

I'm not sure if this is a bug, or the lack of a feature. I would argue that it would be tremendously useful to allow for this.

**Comment by secana** [comment]
Hi, 

not sure if I understood the issue correctly. You cannot publish to the crates.io proxy index `sparse+http://localhost:8000/api/v1/cratesio/`. This index is read only and mirrors the index hosted by https://crates.io.

You can only publish to the Kellnr internal index that is disjoined from the proxy index, e.g. `sparse+http://localhost:8000/api/v1/crates/` (mind the difference between `crates` and `cratesio`).
