### ISSUE TITLE
Way to point to latest for a crate?

### ISSUE THREAD

**Issue by dynamoRando** [kellnr/kellnr#188]
Is there a way to have Kellnr return the latest version of a crate for docs? In other words, something like

```
http://{Kellnr host}/api/v1/docs/{crate name}/latest
```

which would redirect to whatever the latest version is? If not, would a PR to enable such functionality be acceptable?

**Comment by syphar** [comment]
So, I'm not sure how kellnr does this, but here is how docs.rs does it: 
- `latest` is: the latest non-pre, non-yanked version, according to semver. if there is no non-pre version, the latest pre-version is used. yanked versions are never shown with `/latest/` 
- for SEO reasons, we don't redirect to the latest version, but keep `/latest/` in the URL so search engines index this URL. we also set canonical URLs. 
- we also handle semver requirements, with redirects to the version

See also the [current implementation of `match_version`](https://github.com/rust-lang/docs.rs/blob/142d4955af82e0134fd822225bf5a9576746e99f/src/web/mod.rs#L128-L234). And a [current PR where I'm refactoring the logic to look a _little_ better](https://github.com/rust-lang/docs.rs/pull/2383).

**Comment by secana** [comment]
Feature released in kellnr 5.1.2
