### ISSUE TITLE
Admin password

### ISSUE THREAD

**Issue by vikulikov** [kellnr/kellnr#196]
I've set admin password through `KELLNR_SETUP__ADMIN_PWD` env variable and `admin_pwd` param in the toml config. But I'm getting internal server error trying to log in as admin with configured password. Furthermore, `admin` password is still working

**Comment by vikulikov** [comment]
I've restarted and recreated the docker container but it didn't work. But I could change the password successfully with ui

**Comment by secana** [comment]
Works fine when I test it: `docker run --rm -it -p 8000:8000 -e KELLNR_SETUP__ADMIN_PWD="foo" ghcr.io/kellnr/kellnr:5.1.2`

I can login with the password "foo" as the admin user.

**Comment by vikulikov** [comment]
Sorry to bother you. Probably that's because I've mounted data folder. So restarts and recreation of the container didn't help
