### ISSUE TITLE
rustdoc all-features

### ISSUE THREAD

**Issue by snaggen** [kellnr/kellnr#2]
I can't find a way to generate documentation for all features in a crate, it only uses default features. 
With crates.io you can do the following in your Cargo.toml:

[package.metadata.docs.rs]
all-features = true

so, maybe support that?

**Comment by secana** [comment]
Hi @snaggen, thank you for reporting that. Yes, a.t.m only the default feature is build. I'll keep this as the first feature request  for kellnr.

**Comment by syphar** [comment]
I'm excited to see kellnr come to life, and also see it including docs :) 

My 2c about this: 
I believe that over time, the doc-build will at least partially have to replicate docs.rs functionality. 

Probably incomplete examples, from the top of my head, would include: 
- this request here (docs.rs metadata), 
- [`crates-build-env`](https://github.com/rust-lang/crates-build-env) for needed c-libraries for your dependencies. 
- build inside a countainer (probably with [`rustwide`](https://github.com/rust-lang/rustwide) for security (while you probably don't have to care about the source / build-script for your own private packages, you _are_ executing `build.rs` files locally for each dependency they include, which might leak the private source code of your own packages).

**Comment by secana** [comment]
Hi @syphar,

when I build the doc.rs hosting in Kellnr I wanted the most simple solution that works out of the box. For the future, a more sophisticated approach is needed and I don't intend to re-invent the wheel. Using parts of docs.rs in Kellnr would be super cool and keep the docs ecosystem from fragmentation.

If you are interested, a docs.rs + kellnr joint venture would be awesome :)

**Comment by syphar** [comment]
> when I build the doc.rs hosting in Kellnr I wanted the most simple solution that works out of the box. For the future, a more sophisticated approach is needed and I don't intend to re-invent the wheel. Using parts of docs.rs in Kellnr would be super cool and keep the docs ecosystem from fragmentation.
> 

This sounds like a good plan. But keep in mind: there are security implications of the current implementation. As a company, I would want to know this before using kellnr. 


> If you are interested, a docs.rs + kellnr joint venture would be awesome :)

As many projects we have limited capacity, so our topics are different ones right now. But as described, I'm happy to discuss any design / ideas, and review PRs 😃 .

**Comment by secana** [comment]
There is already a big disclaimer in the docs that building docs is basically arbitrary code execution like on any build server.

I would go with multiple steps to incorporate parts from docs.rs. 

1. Replace the raw "rustdoc" call from Kellnr with a library from docs.rs which handles different features and configs for docs.rs
2. Allow Kellnr to switch from a local Rust install to the usage of Docker or something more secure
3. Allow custom build steps (not sure if that is needed), e.g. install native libraries or something else that is not handled by a simple "rustdoc" call

What do you think about that? The first step should be straight forward, if you can provide a library which takes the docs.rs specific config from the Cargo.toml and builds the docs.

**Comment by syphar** [comment]
> There is already a big disclaimer in the docs that building docs is basically arbitrary code execution like on any build server.
> 

I missed that one, sorry about that. 

> I would go with multiple steps to incorporate parts from docs.rs.
> 
>     1. Replace the raw "rustdoc" call from Kellnr with a library from docs.rs which handles different features and configs for docs.rs
> 
>     2. Allow Kellnr to switch from a local Rust install to the usage of Docker or something more secure

sounds good 

> 
>     3. Allow custom build steps (not sure if that is needed), e.g. install native libraries or something else that is not handled by a simple "rustdoc" call
> 

The docs.rs strategy for this will be https://github.com/rust-lang/docs.rs/issues/315 (the crate can provide a custom docker image to build with). 


> 
> What do you think about that? The first step should be straight forward, if you can provide a library which takes the docs.rs specific config from the Cargo.toml and builds the docs.

I'm happy to review any PR to docs.rs that does this, or answer any questions.

**Comment by snaggen** [comment]
I wonder if it would be possible to maybe default to 'all-features' (or add a flag for it) in the short term, since the larger rustdoc rewrite sounds lika a larger thing.

**Comment by secana** [comment]
Enabled in latest release.
