### ISSUE TITLE
Doc queue is accesible when not logged in

### ISSUE THREAD

**Issue by avsaase** [kellnr/kellnr#203]
I just noticed that the doc generation queue is accessible when you are not logged in and `KELLNR_REGISTRY__AUTH_REQUIRED` is set to `true`. Is that intentional? I think it makes sense to protect this route.

**Comment by secana** [comment]
Yes you are right. The route should not be available if the flag it set. I'll fix that for the next version. Thanks for reporting!

**Comment by secana** [comment]
Fixed. New version will be released in the next minutes.
