### ISSUE TITLE
Updating helm values and upgrading, does not change default.toml

### ISSUE THREAD

**Issue by mjo09a** [kellnr/kellnr#231]
I tried updating the helm values (default.toml) but kellnr will not update the changes. I even tried to manually update the configmap and then run helm but the values stayed the same. In order to get the default.toml to change, I had to manually update configmap and then restart the deployment in kubernetes for changes to take effect. I believe this isn't the way it should be done

**Comment by secana** [comment]
Hi. If you use the helm chart, do not change the default.toml. The helm chart has it's own way to set the values with the values.yaml file.

Have a look at the helm documentation here: https://github.com/kellnr/helm
