### ISSUE TITLE
UI bug in search view

### ISSUE THREAD

**Issue by aleksanderkrauze** [kellnr/kellnr#253]
### Description

I have noticed a bug in an UI. When I go to the "search" page and enable listing cached crates there is an inconsistency between view with empty search query, and with filtered crates. When the search input is empty, to the right of each crate name there is its version number, and to the bottom of it a link to its documentation (on docs.rs):

![image](https://github.com/kellnr/kellnr/assets/51295999/c22a9234-9c97-4b8f-a5fa-732added88cc)

But after filtering out crates using search version number is replaced with "vnone", and link to the documentation is replaced with a link to `/publishdocs`.

![image](https://github.com/kellnr/kellnr/assets/51295999/398c3743-3384-456b-876b-16b183f8561c)

This only affects cached crates from crates.io.

### Version

`Kellnr 5.2.0`

**Comment by aleksanderkrauze** [comment]
Oh, and since I have an occasion to do so I must say. Thank you very much for creating this great piece of software!

**Comment by secana** [comment]
Hi! Thanks for reporting the bug. I'll have a look and fix it for the next release.

**Comment by secana** [comment]
Fix is implemented. Will be released with the next version of Kellnr.
