### ISSUE TITLE
Feature Improvement Request: Simplifying Documentation URL Format and Adding Latest Version Link

### ISSUE THREAD

**Issue by IniterWorker** [kellnr/kellnr#286]
I hope this message finds you well. I'm writing to propose some enhancements to the documentation URL format for the kellnr projects. Currently, the documentation URL follows this format:

```bash
http://kellnr.rmds.local/docs/{my-crate-name}/{my-crate-version}/doc/{my-crate-name}/index.html
```

While functional, I believe there's room for improvement for better usability and maintenance.

**Simplification of URL Format:** The current URL format redundantly includes the package name `{my-crate-name}` twice. This duplication doesn't add value and unnecessarily complicates the URL structure. I suggest simplifying the URL to a more direct format to access the documentation:

```bash
http://kellnr.rmds.local/docs/{my-crate-name}/{my-crate-version}/index.html
```

This modification streamlines the URL, making it more intuitive and user-friendly.

**Addition of Latest Version Link:** Another observation is the lack of a direct reference to the latest version of the crate's documentation. Including a link to the latest version documentation is essential for users seeking the most up-to-date information without having to navigate through specific version URLs manually. I propose adding a symbolic link or a redirect to the latest version documentation to facilitate easy access.

I understand that these changes may introduce some breaking adjustments to the URL format. However, the benefits of improved usability and accessibility outweigh the inconvenience of transition.

I would appreciate your thoughts on this proposal, including any additional considerations or ideas for implementation. Thank you for considering these suggestions, and I look forward to your feedback.

**Comment by syphar** [comment]
regarding the "crate name duplication": 

this is actually not a duplication. This second name is actually the target- or package-name and can differ from the crate name. 

Example: https://docs.rs/futures-util/latest/futures_util/ 

The target name is also the name of the top level folder in the rustdoc output. 
So I don't think it's a good idea to work around that separation. 

`/latest/` is one though, but some work.

**Comment by IniterWorker** [comment]
> regarding the "crate name duplication": 
> 
> this is actually not a duplication. This second name is actually the target- or package-name and can differ from the crate name. 
> 
> Example: https://docs.rs/futures-util/latest/futures_util/ 
> 

Good point, then we still need to allow https://docs.rs/futures-util/latest to https://docs.rs/futures-util/latest/futures_util/

**Comment by secana** [comment]
I'm not sure if non-canonical names are still a thing. There was this blog post some time ago: https://blog.rust-lang.org/2023/10/27/crates-io-non-canonical-downloads.html

But even, if the package name differs from the crate name, we could choose one as the identifier and skip the other in the URL or do I miss something?

**Comment by secana** [comment]
API available under `/api/v1/docs/<package>/latest`.
