### ISSUE TITLE
Cannot upload doc

### ISSUE THREAD

**Issue by tomus85** [kellnr/kellnr#287]
I am trying to upload the doc and I have the example curl below 

```sh
curl -H "Authorization: token" \
    http://kellnr.mymachine.uk:8000/api/v1/docs/my_helper/0.1.0 \
    --upload-file doc.zip
```

However, I get this every time
```sh
Wrong number of path arguments for `Path`. Expected 1 but got 2. Note that multiple parameters must be extracted with a tuple `Path<(_, _)>` or a struct `Path<YourParams>`% 
```

How do I fix this? 

Cheers

**Comment by secana** [comment]
Hi @tomus85. Sry for the late response. I'll have a look.

**Comment by secana** [comment]
I tried to recreate the issue but failed.

```bash
cargo doc
cd target
zip -r doc.zip ./doc
curl -H "Authorization: token" http://localhost:8000/api/v1/docs/my_helper/0.1.0 --upload-file doc.zip
```

This uploaded the docs with no issue. Can you give me more information on your setup? Which Kellnr version do you use and can you provide the `Cargo.toml` of your project?

**Comment by tomus85** [comment]
Hey, this is my compose set-up
```sh
version: "3"
name: kellnr
services:
    kellnr:
        ports:
            - 8000:8000
        environment:
            - KELLNR_ORIGIN__HOSTNAME=kellnrhost.<masked>.uk
            - KELLNR_SETUP__ADMIN_PWD=admin
            - KELLNR_SETUP__ADMIN_TOKEN=token
        volumes:
            - /home/<masked>/docker/kellnr/data:/opt/kdata
        image: ghcr.io/kellnr/kellnr:5.0.0
```

Ths is the `Cargo.toml` file 
```sh
[package]
name = "my_helper"
version = "0.1.0"
authors = ["Thomas Curley <masked>"]
edition = "2018"

[dependencies]
```

I push publish this project without any issues.

**Comment by secana** [comment]
I tried to replicate the issue with the additional information, but still failed. It works fine when I try it. I'm sorry, but I have no more ideas how to help you.

**Comment by secana** [comment]
I'll close this issue, but if you have any more ideas what I can try, feel free to reopen it.

**Comment by tomus85** [comment]
Can you give me a snippet of your config? I am still facing this issue
