### ISSUE TITLE
private registry hosting cratesio setup

### ISSUE THREAD

**Issue by guzzijones** [kellnr/kellnr#305]
For others who may want to use kellnr as a private repo hosting crates-io packages here are the settings:
```
# .cargo/config
[source.crates-io]
replace-with = "kellnr-cratesio"

[registries.kellnr-cratesio]
index = "sparse+https://mykellnr.instance.com/api/v1/crates/"

[source.kellnr-cratesio]
registry = "sparse+https://mykellnr.instancecom/api/v1/crates/"

```

the cratesio source needs to point at the `crates` endpoint instead of `cratesio`
`"sparse+https://mykellnr.instancecom/api/v1/cratesio/" will ALWAYS try to go to the internet.

This still doesn't solve the problem of missing `README.md`  on many cargo packages.

**Comment by Christiaan676** [comment]
As far as I can tell everything is documented here: https://kellnr.io/documentation#global-config. 

Kellnr has two endpoints:
For the crates.io proxy: `sparse+https://yourkellnrhostname/api/v1/cratesio/`
For the private registry: `sparse+https://yourkellnrhostname/api/v1/crates/`

In your example your forwarding all the requests for crates.io to the private registry endpoint, that is not going to work.

**Comment by guzzijones** [comment]
we are pulling crates from cratesio and pushing them into kellnr.

**Comment by secana** [comment]
Closed due to inactivity.
