### ISSUE TITLE
Doc build in kellnr docker container fails with: Invalid cross-device link

### ISSUE THREAD

**Issue by jfro** [kellnr/kellnr#313]
I can't just reopen an existing issue otherwise I would do that to #254 as I ran into the same issue while testing out deploying kellnr into a k8s cluster. Doc build died with same invalid cross-device link error as the mentioned issue. Since it sounds like Ubuntu 24.04 fixes it which is now officially out, hoping that might be what happens for next kellnr release?

**Comment by secana** [comment]
I'll update to 24.04 as soon, as GitHub supports the image. Currently the latest version is still 22.04.

**Comment by jfro** [comment]
> I'll update to 24.04 as soon, as GitHub supports the image. Currently the latest version is still 22.04.

glad to hear! stinks waiting for CI hosts to get updates sometimes!

**Comment by makavity** [comment]
@secana hey! Looks like, ubuntu 24-04 is now available :)
https://github.blog/changelog/2024-05-14-github-hosted-runners-public-beta-of-ubuntu-24-04-is-now-available/

**Comment by secana** [comment]
Cool! I'll try to get a new release out in the next days with 24 as the base image. Thanks for linking the blog post. I would have missed it.

**Comment by secana** [comment]
Kellnr with Ubuntu 24.04 is out.

Kellnr 5.2.3
Helm 3.2.3
