### ISSUE TITLE
Can't autogenerate docs when using docker image

### ISSUE THREAD

**Issue by cortopy** [kellnr/kellnr#328]
I just installed kellnr using the helm chart, and the autodoc generation fails with this:

```
2024-05-18T17:26:03.532521Z ERROR docs::doc_queue: Failed to extract docs from crate: could not execute process `rustc -vV` (never executed)
```

I guess it's related to https://github.com/kellnr/kellnr/issues/174. I've checked the Dockerfile, and I don't see rustup installed. Is the command failing because of this?

**Comment by secana** [comment]
Rustup gets installed in the Dockerfile https://github.com/kellnr/kellnr/blob/8b8ad2b124db7a6638f20385a6e046253b1a3d3b/docker/Dockerfile#L13 

I checked that is it present by attaching to the container and `rustc` and `cargo` are available. I'll check if the upgrade to Ubuntu 24.04 or newer `cargo` crate dependency broke something.

**Comment by secana** [comment]
I tried to replicate the issue, but the docs build fine when I uploaded a new crate version. Do you have more information on how to reproduce the issue?
