### ISSUE TITLE
Failed to verify checksum 

### ISSUE THREAD

**Issue by tomus85** [kellnr/kellnr#348]
I have updated a crate and uploaded this to my self-hosted kellnr

However, on another project, I am trying to include the crate I have uploaded (version 0.1.3) and I am seeing this message
`failed to verify the checksum of `<crate name> (registry `kellnr`)`

How do I resolve this? With version 0.1.2 everything was working as normal until I updated to 0.1.3

**Comment by secana** [comment]
Can you provide logs (debug/trace) from kellnr? Which version of kellnr are you on?

**Comment by tomus85** [comment]
I am using kellnr 5.0.0 docker. This was happening on my RPI4. I've set up kellnr again on my Synology NAS, and everything works now.

**Comment by secana** [comment]
Can you update to the latest version of kellnr? There was a change that should prevent the miscalculation of checksums in of of the latest releases.

**Comment by tomus85** [comment]
I have not tested this yet. However, I have managed to update to  5.2.3 so fingers cross it all goes well
