### ISSUE TITLE
Timezone problem within webui

### ISSUE THREAD

**Issue by visig9** [kellnr/kellnr#355]
After upload a crate, I immediately see the crate be noted with "8 hours ago" label in webui. (My browser configured as UTC+8 timezone)

I guess it because `kellnr` using `2024-06-13 01:57:45` UTC timestamp format internally but without explicit mark it with `Z` or `+00:00`. So when parsing by `dayjs`, for example ...

https://github.com/kellnr/kellnr/blob/986c9f31b6f443cdb6c8d63faf036325b4ed5c76/ui/src/components/CrateCard.vue#L56-L58

... the result may incorrect.

`dayjs` has some doc to describe this behavior and show how to fix:
https://day.js.org/docs/en/parse/utc

**Comment by secana** [comment]
@visig9 Thanks for reporting. I'll have a look.

**Comment by secana** [comment]
Fix is in devel. It will be in the next release of kellnr.

**Comment by visig9** [comment]
Sorry not mention all of that. There are still one place I found in code base:

https://github.com/kellnr/kellnr/blob/d73fab9b29db7961aa89be62a3b18e2205cb546c/ui/src/views/Crate.vue#L195-L197
