### ISSUE TITLE
doc build error

### ISSUE THREAD

**Issue by MarcAntoine-Arnaud** [kellnr/kellnr#362]
Hi,

I have started to configure Kellnr.
I'm facing to an issue during doc build a simple crate that depends on serde with derive features (so it depends on proc-macro2).

The server returns and error:
```
   Compiling serde v1.0.203
     Running `rustc --crate-name build_script_build --edition=2018 /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/serde-1.0.203/build.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type bin --emit=dep-info,link -C embed-bitcode=no --cfg 'feature="default"' --cfg 'feature="derive"' --cfg 'feature="serde_derive"' --cfg 'feature="std"' -C metadata=84937f23a642ce8c -C extra-filename=-84937f23a642ce8c --out-dir /opt/kdata/doc_queue/w4yKtF5VYx/frame-rate-0.2.4/target/debug/build/serde-84937f23a642ce8c -L dependency=/opt/kdata/doc_queue/w4yKtF5VYx/frame-rate-0.2.4/target/debug/deps --cap-lints allow`
info: removing previous version of component 'cargo'
info: rolling back changes
error: could not rename component file from '/root/.rustup/tmp/rf1khxy34ifq2i1q_file' to '/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/components'
error: could not rename components file from '/root/.rustup/tmp/omj1re3hn410j1zc_file' to '/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/components': Invalid cross-device link (os error 18)
error: could not compile `proc-macro2` (build script)

Caused by:
  process didn't exit successfully: `rustc --crate-name build_script_build --edition=2021 /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/proc-macro2-1.0.85/build.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type bin --emit=dep-info,link -C embed-bitcode=no --cfg 'feature="proc-macro"' -C metadata=8137b4c4b56919e4 -C extra-filename=-8137b4c4b56919e4 --out-dir /opt/kdata/doc_queue/w4yKtF5VYx/frame-rate-0.2.4/target/debug/build/proc-macro2-8137b4c4b56919e4 -L dependency=/opt/kdata/doc_queue/w4yKtF5VYx/frame-rate-0.2.4/target/debug/deps --cap-lints allow` (exit status: 1)
```

Do you have behaviour for that or if it's a bug ?

Best regards,
Marc-Antoine

**Comment by secana** [comment]
Do you run Kellnr in a container? That behaviour looks like an Docker issue with renaming files.

**Comment by MarcAntoine-Arnaud** [comment]
Yes I try to deploy it using docker, easiest for us. Do you have any recommandations ?

**Comment by MarcAntoine-Arnaud** [comment]
I use the docker image version 5.0.0, but I didn't understand link with source code.
I create an issue to align version in the workspace and with docker image.

**Comment by MarcAntoine-Arnaud** [comment]
It seems related to: https://github.com/kellnr/kellnr/issues/254
The version is a ubuntu jammy (22.04) and not includes bump to the 24.04.

Is it possible to build a new image from recent commits ?
Maybe the main branch may build also a `latest` tag as e pre-candidate release.

**Comment by MarcAntoine-Arnaud** [comment]
I have update to the 5.2.4-rc1 (found here https://github.com/kellnr/kellnr/pkgs/container/kellnr)
But I got same error.

**Comment by MarcAntoine-Arnaud** [comment]
I think an usage of official rust image as base may relevant (regarding that issue https://github.com/rust-lang/rustup/issues/2949, it seems coming from rustup in docker).
Base on `1.79.0-bookworm` seems a good option.

**Comment by MarcAntoine-Arnaud** [comment]
I have open the MR to rework docker build image: https://github.com/kellnr/kellnr/pull/366

**Comment by secana** [comment]
Pipeline with rust base image works in devel. I'll do some more test and than merge to main and release new version of kellnr.
