### ISSUE TITLE
Unable to download index of package "download"

### ISSUE THREAD

**Issue by Christiaan676** [kellnr/kellnr#365]
get https://my kellnr instance/api/v1/cratesio/do/wn/download
```
HTTP/1.1 404 Not Found
Date: Thu, 20 Jun 2024 10:42:11 GMT
Server: Apache
content-length: 0
Connection: close
```
Where:
get https://index.crates.io/do/wn/download
will return a OK and json payload.

This is due to the fact that in `cratesio_api.rs` the download url is registered for `/api/v1/cratesio/*/*/download` and in `cratesio_prefetch_api.rs` the index URL is resisted for `/api/v1/cratesio/*/*/*`. 

Best is to register the paths with so many wild cards on a unique base path. Simplest and backwards compatible solution is to register the download URL as:  `/api/v1/cratesio-registry/*/*/download`.

Found this issue while looking at the code chance that it is a real issue is slim as the crate "download" is yanked. But shows a risk when using wild cards on the same base URL.

For the kellnr private registry there is probably a similar issue. For the crates "download", "yank" and "unyank".

**Comment by secana** [comment]
Good catch!

I'll separate the index and the registry api with a unique base path. Crates.io does it with different sub-domains but that solution won't work well for kellnr.

For the "download", "yank" and "unyank" on the private API: That is not an issue as they are "GET", "DELETE" and "PUT" and as such are different enough.

**Comment by secana** [comment]
As the crate registry protocol (https://doc.rust-lang.org/cargo/reference/registry-web-api.html) expects the registry API to be under `/api/v1/crates/X` I'll move the index to it's own path. This behavior is more similar to the behavior of crates.io where the index is on another sub-domain.

Unfortunately, this is a breaking change, as all clients of Kellnr now have to update their `cargo.toml` files to point to the new index. But I think a more clean solution is worth the break.

TODO: Document the change for a future kellnr 6.0.0 release.

**Comment by Christiaan676** [comment]
Hmmm, I would not really be fond of a breaking change in the API. At work we just migrated from the git index to the sparse index hosted with Kellnr also needing a URL change. Getting a breaking change like this would not be happily received in the organization.

Looking at the [registry documentation](https://doc.rust-lang.org/cargo/reference/registry-index.html) I also get the idea that it  usage of "https://crates.io/api/v1/crates" for the downloads is not what you are required to used.  And setting the `conig.json` `dl` value to 'my-kellnr.com/api/v1/cratesio-registry/' or something completely different is valid.

Looking at the documentation there are 3 API's:
[Index](https://doc.rust-lang.org/cargo/reference/registry-index.html) That specifies that at the configured URL in cargo there should be a config.json at the root and how the URL is build to get the index information for a crate. This is the only URL that needs to remain stable for backwards compatibility. But cargo has no requirements about the base URL. So the `/api/v1/cratesio/` that kellnr uses now is fine (as long as its not classing with the web API). But also not required, hosting it at `/cratesio` is also fine.

[WEB API](https://doc.rust-lang.org/cargo/reference/registry-web-api.html) The config.json 'api' field contains the base URL and the API specifies the extensions to it like: `/api/v1/crates/new`. This API is optional, and mainly used for publishing crates.

The [download API](https://doc.rust-lang.org/cargo/reference/registry-index.html#index-configuration). The `config.json` `dl` field contains the URL that is extended with `/{crate}/{version}/download`. If the `dl` field contains variables like `{crate}` the field is used as is.

So to mine understanding, we only need to keep the index URL's stable. All the other URLS can be moved around provided the `config.json` is filled with the correct values. My suggestion would be to change the `config.json` to for the crates.io proxy:
 
 ```
 {
   "dl":"https://my-kellnr.nl:443/download/v1/cratesio",
   "auth-required":false
}
```
Note I removed the api field,  as the crates.io proxy function does not support publishing. And currently it points to the local kellnr registry and that seams wrong. (Field is optional according to the documentation).

**Comment by secana** [comment]
You are right. It's enough to move the download URL alone. I just implemented it and it seems to work fine. The change will be in the next Kellnr release. No breaking changes needed :)
