### ISSUE TITLE
docqueue gives 401

### ISSUE THREAD

**Issue by marcfir** [kellnr/kellnr#396]
I have deployed Kellnr 5.3.2 via Docker. When logged in as admin, the DevTools of my browser show a 401 for the `/api/v1/docs/queue` call if I click on the docqueue page.

**Comment by secana** [comment]
Can you check if the error still occurs with Kellnr 5.2.3-rc5?

**Comment by marcfir** [comment]
@secana Thanks for the fast response. With Kellnr 5.2.4-rc5 it works fine. All backend calls return 200 and the doc queue shows entries.
