### ISSUE TITLE
An error is logged when, crate does not exists on crates.io

### ISSUE THREAD

**Issue by Christiaan676** [kellnr/kellnr#428]
Looking at the logs (kellnr 5.2.3) I notice the following error:
```
2024-08-20T07:56:58.395391Z ERROR index::cratesio_prefetch_api: Could not parse prefetch data from crates.io for downloax: expected value at line 1 column 1
```
This occurs when a user requests a crate from the proxy that does not exist on crates.io. According to the documentation:

> [Nonexistent Crates](https://doc.rust-lang.org/nightly/cargo/reference/registry-index.html#nonexistent-crates)
> For crates that do not exist, the registry should respond with a 404 “Not Found”, 410 “Gone” or 451 “Unavailable For Legal  Reasons” code.

So 404, 410 or 451 are expected errors, and probably should not be logged as error.

**Comment by secana** [comment]
Thanks for fixing the issue!
