### ISSUE TITLE
Migrate from rocket.rs to axum

### ISSUE THREAD

**Issue by secana** [kellnr/kellnr#51]
# What/Why

Kellnr was started more than three years ago. Rocket.rs was one of the most promising web frameworks at that time. Unfortunatly the development stopped. Axum emerged as a new popular framework with it's roots in the tokio ecosystem, which makes it a perfect fit for Kellnr, as tokio is already heavily used.

# To Do

Kellnr uses rocket.rs for routing, authentication and serving static files. All of this has to be migrated. The list below gives an overview of what has to be done.

The behavior should not change to make the migration as smooth as possible. For nearly all APIs multiple corresponding tests exist.

## Contribute

The branch `migrate-to-axum` is used. If you intend to help with the migration, fork the project and use this branch as the base for your work. Please check the migrated APIs below, such that it is clear what is still missing and work is not done multiple times.

### Root - UI

The root serves mostly UI related APIs.

API

- [x] ui::kellnr_version
- [x] ui::crates
- [x] registry::kellnr_api::me
- [x] ui::search
- [x] ui::statistic
- [x] web_ui::settings::settings
- [x] ui::crates_data
- [x] ui::cratesio_data
- [x] ui::delete 
- [x] ui::build_rustdoc

Tests

- [x] ui::kellnr_version
- [x] ui::crates
- [x] registry::kellnr_api::me
- [x] ui::search
- [x] ui::statistic
- [x] web_ui::settings::settings
- [x] ui::crates_data
- [x] ui::cratesio_data
- [x] ui::delete 
- [x] ui::build_rustdoc

### Static File Server

This route serve static file content, e.g. the user interface for Kellnr.

API

- [x] "/" -> serves "./static"

### User

The user API manages all things related to Kellnr users, for example creating a user or adding a authentication token.

API

- [x] user::login
- [x] user::logout
- [x] user::change_pwd
- [x] user::add
- [x] user::delete
- [x] user::delete_forbidden (still needed?)
- [x] user::reset_pwd
- [x] user::add_token
- [x] user::delete_token
- [x] user::list_token
- [x] user::list_users
- [x] user::login_state

Tests

- [x] user::login
- [x] user::logout
- [x] user::change_pwd
- [x] user::add
- [x] user::delete
- [x] user::delete_forbidden (still needed?)
- [x] user::reset_pwd
- [x] user::add_token
- [x] user::delete_token
- [x] user::list_token
- [x] user::list_users
- [x] user::login_state

### Crates

The API for the crates are implemted under `/api/v1/crates`. This is the heart of Kellnr and allows `cargo` to push and pull crates.

API

- [x] index::kellnr_prefetch_api::prefetch_kellnr
- [x] index::kellnr_prefetch_api::prefetch_len2_kellnr
- [x] index::kellnr_prefetch_api::config_kellnr
- [x] registry::kellnr_api::download
- [x] registry::kellnr_api::publish
- [x] registry::kellnr_api::yank
- [x] registry::kellnr_api::unyank
- [x] registry::kellnr_api::search
- [x] registry::kellnr_api::list_owners
- [x] registry::kellnr_api::add_owner
- [x] registry::kellnr_api::remove_owner

Tests

- [x] index::kellnr_prefetch_api::prefetch_kellnr
- [x] index::kellnr_prefetch_api::prefetch_len2_kellnr
- [x] index::kellnr_prefetch_api::config_kellnr
- [x] registry::kellnr_api::download
- [x] registry::kellnr_api::publish
- [x] registry::kellnr_api::yank
- [x] registry::kellnr_api::unyank
- [x] registry::kellnr_api::search
- [x] registry::kellnr_api::list_owners
- [x] registry::kellnr_api::add_owner
- [x] registry::kellnr_api::remove_owner

### Crates.io

Kellnr can proxy and cache crates.io, as such it dublicates the crates API from above for crates.io

API

- [x] index::cratesio_prefetch_api::prefetch_cratesio
- [x] index::cratesio_prefetch_api::prefetch_len2_cratesio
- [x] index::cratesio_prefetch_api::config_cratesio
- [x] registry::cratesio_api::download
- [x] registry::cratesio_api::search
- [x] ui::delete_cratesio_index

Tests

- [x] index::cratesio_prefetch_api::prefetch_cratesio
- [x] index::cratesio_prefetch_api::prefetch_len2_cratesio
- [x] index::cratesio_prefetch_api::config_cratesio
- [x] registry::cratesio_api::download
- [x] registry::cratesio_api::search
- [x] ui::delete_cratesio_index

### Not Found

Forward all `not found` pages to the `vue.js` router.

- [x] "not found" -> "/static/index.html" -> The `vue.js` router will take over from here

**Comment by jplatte** [comment]
In case it's not known already, [`ServeDir` from `tower-http`](https://docs.rs/tower-http/latest/tower_http/services/struct.ServeDir.html) is the most common solution for serving static files from disk.

There is a [known issue](https://github.com/tokio-rs/axum/issues/1731#issuecomment-1523032952) for automatic redirects (`/static/foo` to `/static/foo/` if `foo` is a directory in the `ServeDir` disk directory), if enabled and `ServeDir` is nested using `nest_service`.

It sounds like you want anything that's not a (known?) API route to go to static file serving though? In that case the `ServeDir` should be added as a `.fallback_service()` on the router, and the issue linked above is irrelevant. There's just one extra thing to note: you need to set an explicit fallback on the api router if you don't want unknown `/api` routes to go to `ServeDir` (since by default fallbacks are inherited by nested routers).

**Comment by secana** [comment]
All APIs are ported and all test work with axum.

Next:

- [ ] Remove all rocket references
- [ ] Test all functionality manually for cases that miss a test

**Comment by secana** [comment]
All test run successfully. Port to axum finished.
