### ISSUE TITLE
Webinterface and docs not guarded by authentication?

### ISSUE THREAD

**Issue by jasontheiler** [kellnr/kellnr#91]
Hi there,

I tried out kellnr yesterday at work, since we are looking for an out-of-the-box solution for a private Rust registry that supports serving documentation. The initial setup using Docker Compose was actually very easy and a quite pleasant experience. The webinterface has a nice aesthetic and it has all features that I'd initially expect. However, some parts of it are a little odd user experience wise. For example, it feels weird that the login page just tells me that I've successfully logged in, but it doesn't redirect me to somewhere that would make sense, like the dashboard or the settings. It also feels weird that various parts of the interface don't update when you navigate away from the page and back. When I want to see up-to-date data, I have to refresh the entire site.

The big problem I have with kellnr however is that the docs and also a lot of other information about the published crates are public and **not** guarded by authentication. Is that on purpose or a bug?

While it's not overly important to protect generic information about a crate, like its name, versions or dependencies, the docs definitely are. Rustdocs not only give deep insight into the source code, but it also allows looking at the source code itself. This makes the required authentication for pulling crates basically useless, since anyone could just get hold of the source code via the docs.

If we wanted to use kellnr as it is right now, we would have to use some other authentication layer on top, to protect the sensitive information. While this is a possible solution, it's certainly not a nice one and to be honest, I wouldn't expect to have to do something like this for a software that advertises itself "to keep my code truly private".

**Comment by secana** [comment]
Hi @jasontheiler,

thank your for your feedback. I'm always happy to hear, where Kellnr can improve.

I created an separate issue for the "no forward on login" problem here #92. I'll try to add an fix for the next version.

Kellnr uses browser side cacheing to keep the number of requests to the backend as low as possible. This means that any change in the backend, e.g. new crate version requires a reload of the page. The reasoning for this, is the assumption that crates are viewed and searched a lot more than new crates are published. Can you specify, where you expected other behavior and what you expect? I'm happy to look into a solution.

For the public pages issue, the short answer is: Yes, that is on purpose. 
The long answer is that when I started to write Kellnr about three years ago, I tried to be as close to crates.io as possible. That means that crates are always public to see in the UI and pull, but require authentication to push.

The "authentication on pull" is a very new feature and in many parts still in the stage of an RFC in cargo. I implemented the current state of the authentication on pull, such that it works with cargo but did not change the behavior of the UI.

I agree with you that people who use the authentication on pull have a different use-case and most likely do not want to have the crate docs public. I created an issue for that here: #93

I'm currently porting Kellnr from rocket.rs to axum, which is an enormous effort and will take some time. After I'm finished with the port, I'll look into improvements and new features.

**Comment by jasontheiler** [comment]
Hi @secana,

I'm glad that we seem to be on the same page about the issues.

> Kellnr uses browser side cacheing to keep the number of requests to the backend as low as possible. This means that any change in the backend, e.g. new crate version requires a reload of the page. The reasoning for this, is the assumption that crates are viewed and searched a lot more than new crates are published.

I would've expected the page to just refetch the data everytime I visit it, instead of showing cached data. As I'm not familiar with the implementation of the HTTP endpoint that provides the data of the published crates, I can't make any statements about its performance. But I can't really imagine that it would have a large impact on overall performance if the page would always fetch fresh data. However, I understand your reason for doing it this way and thus, I can't really call this an issue after all.

I know that required authentication for crate pulls is a bleeding edge feature. I've implemented it myself in our private Rust registry at work. But our version is basically just a tiny HTTP server built with axum that wraps the "generic package registry" of GitLab. So its not nearly as sophisticated and just covers our most basic needs.

**Comment by jasontheiler** [comment]
I'll go ahead and close this issue since there are separate specific issues for the two main problems discussed here now: #92, #93
